### ISSUE TITLE
Question sur le projet rag

### ISSUE THREAD

**Issue by ghost** [lyyf2002/RAG-WIKI#1]
Bonjour!
Svp j'ai essayé d’exécuter votre projet mais j'ai des soucis.
![Capture d’écran du 2024-09-11 12-59-41](https://github.com/user-attachments/assets/bab8a9b6-0103-40df-b862-d5eef4c09c52)
![Capture d’écran du 2024-09-11 12-59-59](https://github.com/user-attachments/assets/5b04ec5f-5d20-46cb-b47f-4d1d9acb4a29)
![Capture d’écran du 2024-09-11 12-59-56](https://github.com/user-attachments/assets/e92b3e9f-7327-4e0e-b6b2-50b34d4928ae)
![Capture d’écran du 2024-09-11 12-59-53](https://github.com/user-attachments/assets/e804cc16-681b-4ce6-ba42-96e78fb4a1ee)
![Capture d’écran du 2024-09-11 12-59-41](https://github.com/user-attachments/assets/948688e7-635c-48d4-bb4c-74643fc6187e)

**Comment by lyyf2002** [comment]
It looks like there is a problem with your openai key
I found a similar problem, because my project uses the free interface of [api.chatanywhere.com.cn](https://api.chatanywhere.com.cn/), maybe you can look at the solution below, or directly replace your api base and api key with the real openai api and your key
[https://github.com/MuiseDestiny/zotero-gpt/issues/239](https://github.com/MuiseDestiny/zotero-gpt/issues/239)

**Comment by ghost** [comment]
Bonsoir!
oui surement merci beaucoup.

**Comment by ghost** [comment]
Bonjour!
svp j'ai besoin encore de votre aide .
J'aimerais savoir est-il possible d'utiliser la base de données de wikipedia dans un projet?

**Comment by lyyf2002** [comment]
You can utilize the complete Wikipedia dataset by following steps 5-7 in the README. However, be aware that it will be costly as the data is nearly 50GB in text, making it challenging to build an index for the full dataset. That's why I only provide a subset here. Or are you suggesting the use of packages like the one at [github.com/goldsmith/Wikipedia](https://github.com/goldsmith/Wikipedia)? If that's the case, the code would need to be rewritten, as it differs from the current codebase. I contemplated this approach when writing the code. If you wish to pursue this, I would be glad to discuss it further with you.

**Comment by ghost** [comment]
Bonjour!
oui je vois d'accord .
oui effectivement merci beaucoup pour votre aide

**Comment by ghost** [comment]
En se qui concerne le sous wiki que vous avez utiliser est en anglais uniquement ou bien en francais?
si c'est en anglais y'a t'il la version francaise?

**Comment by lyyf2002** [comment]
https://dumps.wikimedia.org/frwiki/
download here，and follow the step 5-7， than you can use the fr wiki

**Comment by ghost** [comment]
Ok thank you very much for your help

**Comment by lyyf2002** [comment]
If you still have some problem, email me luoyangyifei@foxmail.com, I will close this issue.
